spring:
  datasource:
    url: jdbc:mysql://49.233.86.230:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Zou@19941205
    type: com.zaxxer.hikari.HikariDataSource
    #单机redis
  redis:
    database: 0
    host: 49.233.86.230
    port: 6379
    password: root
logging:
  level:
    com.qhkj.scm.mapper: debug
mybatis:
  mapper-locations: mapper/*.xml